feat: add video compression setting to config file
yuka-friends/Windrecorder pull request #61
Opened 2023-12-09 02:37 UTC by ASC8384

新增 X265、AV1 编码，支持 qsv、nvenc，支持自定义控制编码质量。
原 4K 视频码率 247 kb/s，压缩到 540P：
<img width="494" alt="13152d88279d7646bc321da204b5aee5" src="https://github.com/yuka-friends/Windrecorder/assets/29878345/d12b474c-60a7-4e0e-ae99-9becf84b9079">

原 4K 视频码率 268 kb/s，压缩到 1080P：
<img width="428" alt="510da2336cc850dc9242cf1695f8cf53" src="https://github.com/yuka-friends/Windrecorder/assets/29878345/28c427f9-7a62-47af-be5d-7559ccc6e893">

2023-12-09 03:06 UTC, ASC8384 commented
```python
import unittest
from record import compress_video_resolution


class Config:
    def __init__(
        self,
        compress_encoder,
        compress_quality,
        compress_accelerator,
    ):
        self.compress_encoder = compress_encoder
        self.compress_quality = compress_quality
        self.compress_accelerator = compress_accelerator


class TestRecord(unittest.TestCase):
    def test_compress_video_resolution(self):
        video_path = "-OCRED.mp4"
        scale_factor = 0.25

        encoder_list = ["x265", "x264", "av1"]
        accelerator_list = ["qsv", "nvenc", "cpu"]
        crf_list = [29, 34, 39, 44]

        if __name__ == "__main__":
            for encoder in encoder_list:
                for crf in crf_list:
                    if encoder == "av1":
                        config = Config(encoder, crf, "cpu")
                        # Call the function to compress the video resolution
                        compress_video_resolution(video_path, scale_factor, config)
                        continue
                    for accel in accelerator_list:
                        config = Config(encoder, crf, accel)
                        compress_video_resolution(video_path, scale_factor, config)


if __name__ == "__main__":
    unittest.main()

```

2023-12-09 09:04 UTC, Antonoko commented
感谢 PR！在此基础上添加了 webui 配置界面：
![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/4515edbf-c814-4499-b562-d75cad09ad39)

2023-12-09 10:30 UTC, ASC8384 commented
Orz，大佬太牛了
~~本来想晚上把 web 的配置写一下的~~
编码器还有用 AMF 的，但我才疏学浅，没机子测试，留待有缘人吧（

2023-12-10 08:10 UTC, jpswing requested changes
感谢贡献！没有什么大问题，修改一些小毛病就好了。

2023-12-10 08:10 UTC, jpswing commented on windrecorder/record.py
> +        output_newname = "compressed_" + encoder + "_" + str(crf) + "_" + os.path.basename(video_path)
使用 f-string

2023-12-10 11:12 UTC, jpswing requested changes

2023-12-10 11:12 UTC, jpswing commented on windrecorder/utils.py
> +    position = keys.index(key) if key in keys else 0  # 查找键的位置，没有则返回1
注释没有修改

2023-12-10 11:12 UTC, jpswing commented on windrecorder/record.py
> +    print(f"[compress_video_CLI] {cmd}")
注意看我的评论，`{cmd}` 和 `{cmd=}` 是不一样的哦

2023-12-10 11:35 UTC, jpswing approved these changes

2023-12-10 11:37 UTC, merged