Add multi-monitor support
yuka-friends/Windrecorder pull request #67
Opened 2023-12-14 02:37 UTC by ASC8384

Using mss to capture multi-monitor screenshot.

2023-12-17 13:26 UTC, Antonoko commented
（我预计下周比较忙，之后抽空看一看 ux 部分是否合理、怎么调整；此外看上去后续可以逐步用 mss 替换掉 pyautogui）

cc @jpswing @hatsuroku 有空时可以先 review 下喵

2023-12-17 13:30 UTC, ASC8384 commented
现在只有`调整屏幕忽略范围的设置可视化`这块还用了`pyautogui`
~~因为不会 UX~~

2023-12-26 04:03 UTC, Antonoko requested changes

2023-12-26 04:03 UTC, Antonoko commented on windrecorder/ui/setting.py
> +            st.session_state.ocr_padding_right = config.ocr_image_crop_URBL[3]
现在 ocr_image_crop_URBL 的数据结构上是如何实现多屏的呢？也许可以把每个屏幕的具体URBL都作为一个列表项，像是有两个屏幕的话为：[[6,6,6,3],[1,2,3,4]]？
（ui上构想是在遮挡选项加一个下拉选单，通过选择不同的显示器进行不同的范围遮挡设定。这个等之后和多屏录制是否启用、选择主屏幕是哪个等一起考虑

2023-12-26 08:32 UTC, ASC8384 commented on config/src/config_default.json
> +  "diy_record": false,
起名字真的太难了 😭

2023-12-26 08:35 UTC, ASC8384 commented on record_screen.py
> +        subprocess.run(' '.join(ffmpeg_cmd), check=True, shell=True)
这里有点问题，因为我使用`diy_record_cmd`来自定义ffmpeg的参数，导致无法使用直接使用参数传入。
```
  "diy_record_cmd": "-c:v libsvtav1 -g 600 -svtav1-params \"fast-decode=1:tbr=400k:rc=1:preset=13:scm=1:lp=4:lookahead=0:fps=2\""
```

2023-12-26 08:38 UTC, ASC8384 commented on windrecorder/ocr_manager.py
> +                break
我没做过性能测试，之所以使用ffmpeg来提取，是因为opencv不支持读取 AV1 编码的视频。
https://forum.opencv.org/t/error-your-platform-doesnt-suppport-hardware-accelerated-av1-decoding-when-i-use-cv2-videocapture/9605

2023-12-26 08:39 UTC, ASC8384 commented on record_screen.py
> +        ffmpeg_cmd = [
如上面提到的，使用`diy_record_cmd`来自定义录制画质，变相解决了 #24 的问题。

2023-12-26 09:06 UTC, Antonoko commented on record_screen.py
> +        ffmpeg_cmd = [
感觉这个最好能通过解耦配置项来实现，而不是让用户覆盖一个ffmpeg命令进去🤔（或者应该给一个配置项让用户是否使用自定义的命令，而对于非geek的用户则可以方便调码率、关键帧率、或极端一些给几档画质预设就可以了）

2023-12-26 09:09 UTC, Antonoko commented on windrecorder/ocr_manager.py
> +                break
如果性能上更佳、结果提取重复度也较低，感觉opencv可以作为一种使用ffmpeg失败后的fallback路径了，这样可能流程更合理一些

2024-01-15 16:31 UTC, Antonoko commented
备忘：
- 目前缩略图使用的是最后的图片处理结果，涂黑遮盖区域可能会导致缩略图看上去不是很好，也会导致后面的图像语义处理不够准确，需要将涂黑结果限定在只允许 OCR 使用；

2024-01-15 16:36 UTC, ASC8384 commented
> 备忘：
> 
>     * 目前缩略图使用的是最后的图片处理结果，涂黑遮盖区域可能会导致缩略图看上去不是很好，也会导致后面的图像语义处理不够准确，需要将涂黑结果限定在只允许 OCR 使用；

该功能应该已实现：

https://github.com/ASC8384/Windrecorder/blob/7e8ce06602fee9d7f7059a78de7a97b81ef904f4/windrecorder/ocr_manager.py#L443C17-L462C18

2024-02-27 09:49 UTC, closed without merging

2024-02-27 09:49 UTC, Antonoko commented
rebase to https://github.com/yuka-friends/Windrecorder/pull/134